### ISSUE TITLE
JKS passwords

### ISSUE THREAD

**Issue by ArmandGazzano** [ec-jrc/cise-sim#3]
Hello,

When I run the simulation, it's asking for jks keys. But you don't give them.
Should I create my own ?

Thank you in advance for your answer.

**Comment by longama** [comment]
Hi Armand, 

 you can find a sample of JKS file (cisesim-nodeex.jks) in the directory:

cise-sim/cise-sim-api/src/test/resources/

along with the file sim.properties that defines the needed properties.
You can always create your own following these instructions:

https://docs.oracle.com/cd/E19509-01/820-3503/ggfen/index.html

Hope this will help.

Reagards,
The JRC-CISE Team

**Comment by ArmandGazzano** [comment]
Hi Longama,

Thanks for your answer. I have created my own keys and it works.

But I have this error:
`[E|Configuration error : Wrong signature configuration : null
eu.cise.sim.dropw.context.ConfigurationException: Wrong signature configuration : null
        at eu.cise.sim.dropw.context.DefaultAppContext.checkConfig(DefaultAppContext.java:296)
        at eu.cise.sim.dropw.context.DefaultAppContext.<init>(DefaultAppContext.java:86)
        at eu.cise.sim.dropw.SimApp.run(SimApp.java:135)
        at eu.cise.sim.dropw.SimApp.run(SimApp.java:64)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at eu.cise.sim.dropw.SimApp.main(SimApp.java:75)](url)`

**Comment by ArmandGazzano** [comment]
Finally I tried with the basic one and it works!

Thanks a lot for your help!
