### ISSUE TITLE
cise/sim send xmf files error

### ISSUE THREAD

**Issue by ArmandGazzano** [ec-jrc/cise-sim#4]
Hello,

When I try to send messages via an xml file, I get an error.
It seems to be a key problem, but it does not ask me to fill the keys.

```
cise/sim send cise/templates/messages/PushTemplate.xml
/home/agazzano/cise/tmp/sim.pid
== CISE sim =====================================
Java path:    /usr/bin/java
Java version: "11.0.13"
=================================================
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/home/agazzano/cise/lib/cise-sim-cli.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" eu.cise.signature.exceptions.SignatureEx: To build a SignatureService object it's mandatory to specify a keystore passwordusing the .withKeyStorePassword(...) method
        at eu.cise.signature.SignatureServiceBuilder.notNullOrEmpty(SignatureServiceBuilder.java:113)
        at eu.cise.signature.SignatureServiceBuilder.build(SignatureServiceBuilder.java:97)
        at eu.cise.cli.CliAppContext.<init>(CliAppContext.java:61)
        at eu.cise.cli.Main.run(Main.java:72)
        at eu.cise.cli.Main.main(Main.java:65)
```

Thanks in advance

**Comment by longama** [comment]
Hi Armand, 

 indeed this is a bug and we have opened an internal issue to solve it. Thank you for your notice.
Anyway you can launch the simulator using the run or start command as indicated in the README.md (https://github.com/ec-jrc/cise-sim#launch-the-cise-sim).

Regards,

The JRC-CISE Team
